llm_model: "gemini-1.5-flash"
embedding_model: "models/embedding-001"
chunk_size: 256
chunk_overlap: 32
prompt: |
  You are an AI assistant tasked with answering a user's query based on retrieved information.
  Read the provided retrieved information to best answer the user's query. If the response is not sufficient, supplement the retrieved information with your knowledge. Then, summarize the provided retrieved information in the context of the query, making your answer sound like a natural, human response. Focus on clarity and conciseness.

  ### Query:
  {query}

  ### Retrieved information:
  {responses}
num_retrival: 5